# https://starship.rs/config/#prompt

# [directory]
# format = '[ $path ]($style)[$read_only]($read_only_style) '
# style = "bold bg:blue"

# https://starship.rs/advanced-config/#statusline-for-claude-code
[profiles]
claude-code = "$directory $git_branch $claude_model $claude_context $claude_cost"

[claude_context]
# format = "[$percentage (↑$input_tokens ↓$output_tokens)]($style) "
display = [
    { threshold = 0, style = "green" },
    { threshold = 60, style = "yellow" },
    { threshold = 80, style = "red" },
]
gauge_full_symbol = "■"
gauge_partial_symbol = ""
gauge_empty_symbol = "□"
gauge_width = 10
format = "[$percentage $gauge]($style) [↑]($style bold) [$input_tokens]($style) [↓]($style bold) [$output_tokens]($style)"

[claude_cost]
display = [{ style = "yellow" }]
format = "[$symbol]($style bold) [$cost]($style) "
symbol = "$ "
