# https://starship.rs/config/#prompt

format = "$hostname${custom.username}$all"

[custom.username]
command = "whoami 2>/dev/null || printf unknown"
when = true
format = "[ 󰌾 $output ]($style)[](bright-black) "
style = "fg:white bg:bright-black"

[hostname]
ssh_only = false
format = "[](white)[  $hostname ]($style)[](fg:white bg:bright-black)"
style = "fg:bright-black bg:white"

[directory]
style = "bold dimmed"
format = "[ $path]($style)[$read_only]($read_only_style) "
truncation_length = 0
truncate_to_repo = true

repo_root_style = "bold blue"
repo_root_format = "[ $repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[❯](bold dimmed yellow)"
error_symbol = "[❯](bold red)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold green"
symbol = " "

[git_status]
style = "dimmed bright-green"

[cmd_duration]
format = "[󰔛 $duration]($style) "

[package]
format = "[$symbol$version]($style)\n"
style = "dimmed bright-yellow"
symbol = " "

[nodejs]
format = "[$symbol](green)[$version]($style) "
style = "dimmed bright-green"
symbol = " "

[python]
format = '[$symbol](yellow)[${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "dimmed bright-yellow"
symbol = " "

[rust]
format = "[$symbol](red)[$version]($style) "
style = "dimmed bright-red"
symbol = " "

[aws]
format = '[$symbol](yellow)[($profile )(\($region\) )(\[$duration\] )]($style)'
style = "dimmed bright-yellow"
symbol = " "

# https://starship.rs/advanced-config/#statusline-for-claude-code
[profiles]
claude-code = "$directory$git_branch\n$claude_model $claude_context $claude_cost"

[claude_context]
# format = "[$percentage (↑$input_tokens ↓$output_tokens)]($style) "
display = [
  { threshold = 0, style = "green" },
  { threshold = 25, style = "yellow" },
  { threshold = 50, style = "red" },
]
gauge_full_symbol = "█"
gauge_partial_symbol = "▓"
gauge_empty_symbol = "░"
gauge_width = 10
format = "[$percentage $gauge]($style) [↑]($style bold) [$input_tokens]($style) [↓]($style bold) [$output_tokens]($style)"

[claude_model]
format = "[$model]($style) "
style = "bold blue"

[claude_cost]
display = [{ style = "yellow" }]
format = "[$symbol]($style bold) [$cost]($style)"
symbol = "\\$"
